/*[17:45:12][463 ms]
 * 改变device_device表DEVICESTATUS字段类型
 **/ 
 ALTER TABLE `iot`.`device_device` CHANGE `DEVICESTATUS` `DEVICESTATUS` INT(10) NOT NULL COMMENT '设备状态';
 
 /**
  * [11:29:07][753 ms]
  * 修改SUPERVISEVALUE SUPERVISEVALUE2字段类型为varchar
  * */ 
 
ALTER TABLE `iot`.`supervise_supervise` CHANGE `SUPERVISEVALUE` `SUPERVISEVALUE` VARCHAR(10) CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '参数一值', CHANGE `SUPERVISEVALUE2` `SUPERVISEVALUE2` VARCHAR(10) CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '参数二值'; 
