CREATE TABLE `notice_notice` (
  `ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `TITLE`  VARCHAR(50) NOT NULL,
  `CONTENT` MEDIUMTEXT NOT NULL,
  `RECEIPTSIGN` TINYINT(4) NOT NULL,
  `REGDEADLINE` TIMESTAMP NULL DEFAULT NULL,
  `AUTHOR` INT(10) UNSIGNED NOT NULL,
  `POSTDATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `EDITDATE` TIMESTAMP NULL DEFAULT NULL,
  `EDITAUTHOR` INT(10) UNSIGNED DEFAULT NULL,
  `STATUS` VARCHAR(10) COLLATE utf8mb4_unicode_ci NOT NULL,
  `ISPUBLISHED` TINYINT(4) NOT NULL,
  `ISDELETED` TINYINT(4) DEFAULT NULL,
   PRIMARY KEY (`ID`) USING BTREE,
   KEY `FK_NOTICE_NPAUTHOR` (`AUTHOR`),
   KEY `FK_NOTICE_NPEDITAUTHOR` (`EDITAUTHOR`),
   CONSTRAINT `FK_NOTICE_NPAUTHOR` FOREIGN KEY (`AUTHOR`) REFERENCES `user_user` (`ID`) ON DELETE CASCADE,
   CONSTRAINT `FK_NOTICE_NPEDITAUTHOR` FOREIGN KEY (`EDITAUTHOR`) REFERENCES `user_user` (`ID`) ON DELETE CASCADE
   )ENGINE=INNODB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
  
  
