/*
SQLyog Ultimate v11.11 (32 bit)
MySQL - 5.6.24-log : Database - socialbiz
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
/*Table structure for table `receipt_baseinfo` */

DROP TABLE IF EXISTS `receipt_baseinfo`;

CREATE TABLE `receipt_baseinfo` (
  `ID` int(10) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `NOTICEID` int(10) NOT NULL COMMENT '通知主键',
  `COMPANYID` int(10) NOT NULL COMMENT '企业主键',
  `USERID` int(10) NOT NULL COMMENT '回执人主键',
  `RECEIPTTIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '回执时间',
  `WILLNUM` int(10) NOT NULL COMMENT '报名人数',
  `SOURCE` int(4) NOT NULL DEFAULT '0' COMMENT '来源（0：移动端；1：WEB端；默认为0）',
  `TYPE` int(4) NOT NULL DEFAULT '0' COMMENT '类型（0：报名；默认为0）',
  `REMARKS` varchar(300) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '备注',
  `EDITOR` int(10) DEFAULT NULL COMMENT '编辑人主键',
  `EDITORTIME` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '编辑时间',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
